export enum AnalyticsCategory {
  FAQ_COLLAPSABLE_OPENED = 'FAQ_COLLAPSABLE_OPENED',
  WILLHABEN_LINK_CLICKED = 'WILLHABEN_LINK_CLICKED',
  WILLHABEN_BUTTON_CLICKED = 'WILLHABEN_BUTTON_CLICKED',
  IMPRINT_LINK_CLICKED = 'IMPRINT_LINK_CLICKED',
  IMPRINT_BACK_BUTTON_LINK_CLICKED = 'IMPRINT_BACK_BUTTON_LINK_CLICKED',
  PAYMENT_LINK_CLICKED = 'PAYMENT_LINK_CLICKED',
  PAYMENT_BACK_BUTTON_LINK_CLICKED = 'PAYMENT_BACK_BUTTON_LINK_CLICKED',
}
